#!/bin/sh
#
# keystone  OpenStack Identity Service
#
# chkconfig:   - 98 02
# description: keystone works provide apis to  \
#		* Authenticate users and provide a token \
#		* Validate tokens
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=keystone
exec="/usr/bin/$prog-all"
config="/etc/$prog/$prog.conf"
distconfig="/usr/share/$prog/$prog-dist.conf"
pidfile="/var/run/$prog/$prog.pid"
startuplog="/var/log/$prog/$prog-startup.log"
timeout=60
wrapper="/usr/share/$prog/daemon_notify.sh"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user keystone --pidfile $pidfile "$wrapper $exec $pidfile $startuplog $timeout"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
